#!/bin/bash
# =============================================================================
# プラットフォーム自動判定 & docker-compose.override.yml 生成
# =============================================================================
# devcontainer.json の "initializeCommand" からホスト側で実行される。
# OS と NVIDIA GPU の有無を判定し、適切な override ファイルを生成する。
#
# 判定ロジック:
#   macOS        → CPU モード (GPU パススルー不可)
#   WSL2         → NVIDIA GPU があれば GPU モード、なければ CPU モード
#   Linux (bare) → NVIDIA GPU があれば GPU モード、なければ CPU モード
# =============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OVERRIDE_FILE="${SCRIPT_DIR}/docker-compose.override.yml"

# ---------------------------------------------------------------------------
# OS 判定
# ---------------------------------------------------------------------------
detect_platform() {
  case "$(uname -s)" in
    Darwin)
      PLATFORM="macOS"
      ;;
    Linux)
      if grep -qi microsoft /proc/version 2>/dev/null; then
        PLATFORM="WSL2"
      else
        PLATFORM="Linux"
      fi
      ;;
    MINGW*|MSYS*|CYGWIN*)
      PLATFORM="Windows"
      ;;
    *)
      PLATFORM="Unknown"
      ;;
  esac
}

# ---------------------------------------------------------------------------
# NVIDIA GPU 判定
# ---------------------------------------------------------------------------
detect_nvidia_gpu() {
  HAS_GPU=false

  if [ "$PLATFORM" = "macOS" ]; then
    return
  fi

  if command -v nvidia-smi &>/dev/null && nvidia-smi &>/dev/null; then
    if docker info 2>/dev/null | grep -qi "nvidia"; then
      HAS_GPU=true
    elif docker run --rm --gpus all nvidia/cuda:12.0-base nvidia-smi &>/dev/null 2>&1; then
      HAS_GPU=true
    fi
  fi
}

# ---------------------------------------------------------------------------
# docker-compose.override.yml 生成
# ---------------------------------------------------------------------------
generate_override() {
  if [ "$HAS_GPU" = true ]; then
    echo "  -> Generating override: NVIDIA GPU enabled"
    cat > "$OVERRIDE_FILE" <<'YAML'
# Auto-generated by setup-platform.sh — NVIDIA GPU detected
services:
  ollama:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
YAML
  else
    echo "  -> Generating override: CPU mode"
    cat > "$OVERRIDE_FILE" <<'YAML'
# Auto-generated by setup-platform.sh — CPU mode
services: {}
YAML
  fi
}

# ---------------------------------------------------------------------------
# メイン
# ---------------------------------------------------------------------------
echo ""
echo "=== Webhook Analyzer: Platform Detection ==="
echo ""

detect_platform
echo "  Platform: ${PLATFORM}"

detect_nvidia_gpu
echo "  NVIDIA GPU: ${HAS_GPU}"

generate_override

echo ""
echo "  Override: ${OVERRIDE_FILE}"
echo ""
